server:
    port: 8082
spring:
    application:
        name: cloud-security
    mvc:
      static-path-pattern: /static/**
#    datasource:
#        url:jdbc:mysql://39.108.137.88:3306/jinfang?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#        username:root
#        password:123456

