eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8766

spring:
  application:
    name: consumer-feign

  session:
      store-type: redis
      redis:
        flush-mode: immediate
        namespace: spring:session

  redis:
  # 单机redis配置
  #    host: localhost
  #    password:
  #    port: 6379

  #    集群redis配置
    cluster:
      nodes: 192.168.204.130:7000,192.168.204.130:7001,192.168.204.130:7002
      max-redirects: 3
    jedis:
      pool:
        max-active: 50
        max-idle: 8

feign:
  hystrix:
    enabled: true