server:
  port: 8002

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ssnhqzj/spring_cloud_config/
          search-paths: config
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/