server:
  port: 8762

spring:
  application:
    name: eureka-client #ribbon名称不支持下划线_

  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: spring:session

  redis:
    cluster:
      nodes: 192.168.204.129:7000,192.168.204.129:7001,192.168.204.129:7002
      max-redirects: 3
    jedis:
      pool:
        max-active: 50
        max-idle: 8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/